[host]
anthem_cli_path = C:\Program Files\AnthemScore\AnthemScore.exe
destination_directory = C:\Users\...\Music\AnthemScore
[analysis]
# note all outputs use the  --musicxml and --asdt options in the destination_directory
anthem_cli_options = --headless

[pedal]
music_directory_globs = C:\Users\...\Music\**\*.wav
